---
output:
  word_document: default
  html_document: default
  pdf_document: default
---

####################################################################
#UNIVERSITY : STEVENS INSTITUE OF TECHNOLOGY
#Project : HW 06 C50 and RF Decision Tree  
#Purpose : Use the C50 & Random forest Tree methodology to develop a classification models 
#First Name : Sarthak
#Last Name : Ahir
#CWID : 10479028
#Date : 11/15/2021
####################################################################
rm(list=ls())


#installing the required libraries
library(C50)

#Load the “breast-cancer-wisconsin.csv” from canvas into R and perform the analysis

newDataSet = read.csv("~/Downloads/breast-cancer-wisconsin.csv",na.strings = '?')


#Summarizing each column 
summary(newDataSet)
table(newDataSet$Class)

View(newDataSet) 


#Convert labels to factor class
newDataSet$Class<- factor(newDataSet$Class , levels = c("2","4") , labels = c("Benign","Malignant"))

#Omitting the NA values
newDataSet<-na.omit(newDataSet)


# Splitting the newDataSet Data to test and training

Data<-sort(sample(nrow(newDataSet),as.integer(.70*nrow(newDataSet))))

training<-newDataSet[Data,]

test<-newDataSet[-Data,]

dev.off()

# Implementing C - 5.0

C50<-C5.0(Class~.,training[,-1])

summary(C50)

plot(C50)

#predicting using the created test data

predictedValue<-predict(C50,test[,-1],type="class") 

#Generating the confusion matrix

confusionMatrix<-table(test[,11],predictedValue)

confusionMatrix
str(predictedValue)

# error rate 

valueC50<-sum(test[,11]!=predictedValue)
errorRate<-valueC50/length(test[,11])

errorRate
# error rate in percent
print(paste("the error rate is",errorRate*100))

#######   Random Forest   #######   

#installing the required libraries
library(randomForest)

# Applying random forest
dataRF <- randomForest( Class~., data=training, importance=TRUE, ntree=1000)
importance(dataRF)
varImpPlot(dataRF)

#predicting using the created test data for Random Forest

predictionRF <- predict(dataRF, test)
table(actual=test$Class,predictionRF)

# error rate 

valueRF<- (test$Class!=predictionRF )

errorRate<-sum(valueRF)/length(valueRF)
errorRate 
# error rate in percent
print(paste("the error rate is",errorRate*100))



##install.packages('XQuartz',repos='http://cran.us.r-project.org')


