---
output:
  word_document: default
  html_document: default
  pdf_document: default
---

####################################################################
#UNIVERSITY : STEVENS INSTITUE OF TECHNOLOGY
#Project : HW_09_SVM
#Purpose : Use SVM methodology to develop a classification model
#First Name : Sarthak
#Last Name : Ahir
#CWID : 10479028
#Date : 12/06/2021
####################################################################
rm(list=ls())
dev.off
#Clear all graphs
try(dev.off(),silent=TRUE)


#Load the “wisc_bc_ContinuousVar” from canvas into R and perform the analysis

newDataSet<-read.csv("~/Downloads/wisc_bc_ContinuousVar.csv")

#Summarizing each column 
summary(newDataSet)
table(newDataSet$Class)

View(newDataSet) 

#deleting first row
newDataSet = subset(newDataSet, select = -c(id) )

#Fasctorising the diagnoasis column 
newDataSet$diagnosis <- factor(newDataSet$diagnosis, levels = c('M','B'),labels = c(1,2))

#Splitting the dataet into training and testing 
index<-sort(sample(nrow(newDataSet),as.integer(.70*nrow(newDataSet))))
train<-newDataSet[index,]
test<-newDataSet[-index,]

#Perfroming SVM 
library(e1071)
svm.model <- svm( diagnosis~ ., data =train  )
svm.pred <- predict(svm.model,  test )

#Confusion matrix 
confusion_matrix <- table(predict_svm=svm.pred,class=testing$diagnosis)
print(confusion_matrix)

#Accuracy 
accuracy <- function(x){sum(diag(x)/(sum(rowSums(x)))) * 100}
accuracy(confusion_matrix)






